name: Test JIRA
on: [push]

jobs:
  test-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Push Deployment Info to Jira
        uses: HighwayThree/jira-upload-deployment-info@7cd4db1e5cc96692fd0b4c688407efd95ae3e610
        with:
          client-id: '${{ secrets.JIRA_CLIENT_ID }}'
          client-secret: '${{ secrets.JIRA_CLIENT_SECRET }}'
          cloud-instance-base-url: '${{ secrets.JIRA_CLOUD_INSTANCE_BASE_URL }}'
          issue-keys: "ED-1269,ED-3134,ARCH-30"
          display-name: "3.3.0-dev6"
          url: 'https://github.com/elementor/elementor/actions/runs/859988518'
          description: "This PR was merged to the following release(s)"
          last-updated: '2021-05-20T10:07:20Z'
          state: 'successful'
          pipeline-url: 'https://github.com/elementor/elementor/actions/runs/859988518'
          environment-id: "3.3.0-dev6"
          environment-display-name: "3.3.0-dev6"
          environment-type: 'staging'
